// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi2ZuQL61zcbCh822wzc0AeJou0jcVOWU',
    appId: '1:44353304597:web:6a701b10d3a28480ab761c',
    messagingSenderId: '44353304597',
    projectId: 'jarnamaapp',
    authDomain: 'jarnamaapp.firebaseapp.com',
    storageBucket: 'jarnamaapp.appspot.com',
    measurementId: 'G-8LRKCW58V6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj_7BFSyOVS7Yyy7wMglkdAC6UvDncLwM',
    appId: '1:44353304597:android:f0ad19b1a509dd42ab761c',
    messagingSenderId: '44353304597',
    projectId: 'jarnamaapp',
    storageBucket: 'jarnamaapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCugOyhOhgZ57SFLnVbDRyuLCohmW7CGGA',
    appId: '1:44353304597:ios:a6e114ceef8790c7ab761c',
    messagingSenderId: '44353304597',
    projectId: 'jarnamaapp',
    storageBucket: 'jarnamaapp.appspot.com',
    iosClientId: '44353304597-a6q8igtve2adoq27i1cevoc3nrm5t504.apps.googleusercontent.com',
    iosBundleId: 'com.example.jarnamaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCugOyhOhgZ57SFLnVbDRyuLCohmW7CGGA',
    appId: '1:44353304597:ios:8d4165e14a4aa489ab761c',
    messagingSenderId: '44353304597',
    projectId: 'jarnamaapp',
    storageBucket: 'jarnamaapp.appspot.com',
    iosClientId: '44353304597-38r1dpc2071n9lmaietu8jdngdc6ld4c.apps.googleusercontent.com',
    iosBundleId: 'com.example.jarnamaApp.RunnerTests',
  );
}
